CREATE TABLE account
(
	a_id BIGSERIAL PRIMARY KEY,
	a_name VARCHAR(30) NOT NULL,
	a_surname VARCHAR(30) NOT NULL
	a_email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE topic
(
	t_id BIGSERIAL PRIMARY KEY,
	t_title VARCHAR(100) NOT NULL UNIQUE,
	t_user_id BIGINT NOT NULL REFERENCES account(a_id),
);

CREATE TABLE subtopic
(
	sub_id BESERIAL PRIMARY_KEY,
	sub_title VARCHAR(100) NOT NULL UNIQUE,
	sub_group_id BIGINT NOT NULL REFERENCES group(t_id)
);

CREATE TABLE card
(
	c_id BIGSERIAL PRIMARY KEY,
	c_question VARCHAR(200) NOT NULL,
    	c_answer VARCHAR(200) NOT NULL,
	c_isremember BOOLEAN NOT NULL,
	c_group_id BIGINT NOT NULL REFRENCES subgroup(sub_id),
);
